// XSI SETUP VERSION INFORMATION
#define XSI_WPROMPT_STRING "WXSI"
#define XSI_APPLICATION_NAME "SciOS-XSI"
#define XSI_COMMAND_PROMPT "xsi> "
#define XSI_VERSION_STRING "2.1.0"
#define XSI_VERSION_FLOAT 2.10
#define XSI_CREATION_DATE_STRING "01-SEP-1998"
#define XSI_BANNER_STRING "SciOS XSI/CLIPS V 2.1.0 (Rel. 22-AUG-2013)\n\n" 
#define XSI_MAC_CREATOR_STRING "scios"
#define XSI_MAC_CREATOR_CODE 'scios'

// PACKAGE AND VERSION INFORMATION
//#define XSI_VERSION_FLOAT 1.65
//#define XSI_CLIPS_VERSION "6.30"
//#define XSI_SQLITE3_VERSION "3.6.6.1"
//#define XSI_WSOCK_VERSION "wsock32"
//#define XSI_SCHEME_VERSION "scheme"
//#define XSI_IUP_VERSION "3.0"
// [CLIPS 6.30, PgSQL 8.3.5, sqlite3 3.6.6.1, wsock32, scheme, IUP 3.0]
